### ISSUE TITLE
Ignite website has been down for a while

### ISSUE THREAD

**Issue by matthewv** [ignitejs/ignite#8]
Ignite website link "http://ignitejs.com/" for doc's has been down for a while. Are you able to fix the website this is an excellent resource or alternativly put this as a doc in the git repo!

thanks.

**Comment by hammonda** [comment]
Hi, sorry about the site being down, I will look into it. 

For now, you can run the site locally (on port 8080 for example). Just unpack the latest [web archive](https://github.com/ignitejs/ignite/tree/master/web) and run
```
$ npm install
$ node server.js 8080
```

**Comment by matthewv** [comment]
Thanks very much that works well!

_PS: Change of telephone number_
Due to a phone system upgrade, my new (land-line) telephone number is +64
(0)6 280 2832 <++64+(0)6%C2%A0280+2832>.
Our previous land-line number(s) will shortly become obsolete, so you may
wish to update your records.

Cheers,

Matthew

http://www.betasolutions.co.nz/

_Matthew van der Werff_ (PhD)
Technical Director

*Beta Solutions Ltd *| *PARTNERS IN PRODUCT INNOVATION *

_T_ +64 (0)6 280 2832 <6462802832> | _M *+64 (0)21 102 1970 <0211021970> |
*E_ matthew@betasolutions.co.nz | _W_ www.betasolutions.co.nz | _L_ Location
Map
http://maps.google.com/?f=q&source=s_q&hl=en&geocode=&q=Beta+Solutions+Ltd+Palmerston+North+Manawatu-wanganui+New+Zealand&sll=-40.375059,175.615168&sspn=0.013045,0.01929&ie=UTF8&hq=Beta+Solutions+Ltd&hnear=Palmerston+North,+New+Zealand&cid=14830261900149245949&ll=-40.360018,175.614052&spn=0.065402,0.085831&z=13&output=embed

_P_ostal   | PO Box 1210, Palmerston North 4440, New Zealand |

_C_ourier | C/- The Factory, 21 Dairy Farm Road, Palmerston North 4472, New
Zealand |

_Working with innovative businesses and entrepreneurs to help transform
their ideas into reality_
